KNN as classifier on iris data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('./Data/Iris.csv')
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,5].values

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=8)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [7]:
y_pred=classifier.predict(x_test)

In [8]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
print("Confusion matrix :\n")
print(result)
result1=classification_report(y_test,y_pred)
print('\nClassification report :\n');
print(result1)
result2=accuracy_score(y_test,y_pred)
print(f'Accuracy : {result2:.5f}')

Confusion matrix :

[[12  0  0]
 [ 0 12  0]
 [ 0  2 19]]

Classification report :

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.86      1.00      0.92        12
 Iris-virginica       1.00      0.90      0.95        21

       accuracy                           0.96        45
      macro avg       0.95      0.97      0.96        45
   weighted avg       0.96      0.96      0.96        45

Accuracy : 0.95556
